#!name=BaiduPan
#!desc=百度网盘倍速清晰度

[Script]
bdpan.unlock = type=http-request, pattern=https:\/\/pan\.baidu\.com\/api\/streaming\?app_id=\d+&type=M3U8_HQ_1080, script-path=https://ddgksf2013.top/scripts/bdpan.unlock.js, timeout=60

bdpan.unlock = type=http-response, pattern=https:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user, script-path=https://ddgksf2013.top/scripts/bdpan.unlock.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = pan.baidu.com, *.pcs.baidu.com, *.baidu.com
